### ISSUE TITLE
mooltiapp opens TCP port 30035 externally!

### ISSUE THREAD

**Issue by randomisresistance** [limpkin/mooltiapp#25]
Hi, 

I just figured out that the mooltiapp is opening a tcp port externally.

_nmap -sT -p - 192.168.1.2
Starting Nmap 7.01 ( https://nmap.org ) at 2017-06-15 22:18 CEST
Nmap scan report for 10.0.0.2
Host is up (0.000027s latency).
Not shown: 65533 closed ports
PORT      STATE SERVICE
22/tcp    open  ssh
**30035/tcp open  unknown**_

_netstat -lntp
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.1.1:53            0.0.0.0:               LISTEN      -               
tcp        0      0 0.0.0.0:22              0.0.0.0:               LISTEN      -               
tcp        0      0 127.0.0.1:15550         0.0.0.0:               LISTEN      -               
tcp        0      0 127.0.0.1:8200          0.0.0.0:               LISTEN      2956/Duplicati  
tcp        0      0 127.0.0.1:8300          0.0.0.0:               LISTEN      9204/Duplicati  
tcp6       0      0 :::22                   :::                    LISTEN      -               
**tcp6       0      0 :::30035                :::                    LISTEN      22885/preload.js --**_

After some short digging I found the line that does this.
[app/preload.js](https://github.com/limpkin/mooltiapp/search?utf8=%E2%9C%93&q=30035&type=)
It is really necessary to bind this port to a any interface rather than localhost?

Cheers,
RandomIsResistance

**Comment by limpkin** [comment]
Hello there,

You are indeed right, it may be better practise to open it locally.

On Jun 15, 2017 20:47, "randomisresistance" <notifications@github.com>
wrote:

Hi,

I just figured out that the mooltiapp is opening a tcp port externally.

`nmap -sT -p - 192.168.1.2

Starting Nmap 7.01 ( https://nmap.org ) at 2017-06-15 22:18 CEST
Nmap scan report for 10.0.0.2
Host is up (0.000027s latency).
Not shown: 65533 closed ports
PORT STATE SERVICE
22/tcp open ssh
*30035/tcp open unknown*
`

netstat -lntp (Not all processes could be identified, non-owned process
info will not be shown, you would have to be root to see it all.) Active
Internet connections (only servers) Proto Recv-Q Send-Q Local Address
Foreign Address State PID/Program name tcp 0 0 127.0.1.1:53 0.0.0.0:*
LISTEN - tcp 0 0 0.0.0.0:22 0.0.0.0:* LISTEN - tcp 0 0 127.0.0.1:15550
0.0.0.0:* LISTEN - tcp 0 0 127.0.0.1:8200 0.0.0.0:* LISTEN 2956/Duplicati
tcp 0 0 127.0.0.1:8300 0.0.0.0:* LISTEN 9204/Duplicati tcp6 0 0 :::22 :::*
LISTEN - **tcp6 0 0 :::30035 :::* LISTEN 22885/preload.js --**

After some short digging I found the line that does this.
app/preload.js
<https://github.com/limpkin/mooltiapp/search?utf8=%E2%9C%93&q=30035&type=>
It is really necessary to bind this port to a any interface rather than
localhost?

Cheers,
RandomIsResistance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/limpkin/mooltiapp/issues/25>, or mute the thread

**Comment by limpkin** [comment]
A PR is ready, I can't approve it until we're back from holidays.

**Comment by randomisresistance** [comment]
Wow,

thats a fast reaction!  :+1:   
Thanks for the support and enjoy the rest of your holiday!

**Comment by limpkin** [comment]
2.0.80 just pushed with that fix!
